### ISSUE TITLE
misplaced option value pointer

### ISSUE THREAD

**Issue by queen3** [highkite/pdfAnnotate#10]
I get this error when trying to pdfFactory.getAnnotations() for the loaded https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf file.

In fact I get it on my own file, too, but I found few other files where it happens, including the Adobe's one above.

Can you give some clues on what can be the problem before I dive too deep into the PDF specs?

Here's the stack trace just in case

extractOptionValue (util.ts:309)
extractArray (array-util.ts:48)
extractDictValueRec (object-util.ts:46)
extractDictKeyRec (object-util.ts:32)
extractDictValueRec (object-util.ts:89)
extractDictKeyRec (object-util.ts:32)
extractDictValueRec (object-util.ts:89)
extractDictKeyRec (object-util.ts:32)
extractDictValueRec (object-util.ts:61)
extractDictKeyRec (object-util.ts:32)
extractDictValueRec (object-util.ts:63)
extractObject (object-util.ts:123)
CatalogObject (parser.ts:118)
getCatalog (parser.ts:311)
getPageTree (parser.ts:345)
getPage (parser.ts:362)
createBaseAnnotation (annotation.ts:130)
createSquareCircleAnnotation (annotation.ts:313)
createCircleAnnotation (annotation.ts:351)
(anonymous) (pdfjsExample.html:242)

**Comment by highkite** [comment]
Hey @queen3 . Thank you for your report and the document. There were a number of issues in the parser. I fixed those. 

In my tests your document is working now and the number of unit tests increases steadily ;)
