### ISSUE TITLE
Specify fill color for createSquareAnnotation()

### ISSUE THREAD

**Issue by anish01stha** [highkite/pdfAnnotate#11]
Is there a way to put fill color in createSquareAnnotation() function to cover/hide text or is there consideration for it to be added later on?

**Comment by highkite** [comment]
@anish01stha  Will be part of the next version

**Comment by ccc159** [comment]
@highkite Thanks for the amazing tool! Really simple and effective. I have the same need to fill rectangle or polygon with colors.  It would be even better to be able to change stroke width, and add color alpha channel.

I wonder if there is a schedule for the update? I thought about tweaking it myself, but the [writer](https://github.com/highkite/pdfAnnotate/blob/master/src/writer.ts) seams Greek to me.

**Comment by ccc159** [comment]
I do see the [`opacity`](https://github.com/highkite/pdfAnnotate/blob/3a6d5464138e30c413535a9060f63294b58a8c7c/src/parser.ts#L51), which is not exposed, but should be fairly simple to do. But couldn't find which one is `filling` though.

**Comment by highkite** [comment]
Version 1.0.13 now supports fill color configuration. I will look into passing through the other configuration flags next.

**Comment by ccc159** [comment]
@highkite Thanks for the update! Already using it! Would it be possible to also add `fill` option for `createPolygonAnnotation`?

**Comment by highkite** [comment]
Supported by version 1.0.14
