### ISSUE TITLE
Contact info?

### ISSUE THREAD

**Issue by ObjectJosh** [highkite/pdfAnnotate#13]
Hey Thomas, I recently found your alphaBot repo pretty interesting, since I'm getting interested in image recognition. Can I ask you some questions about the project? I couldn't find any contact info I could reach you with... but I was wondering if I could message you through email or discord? --Thanks!!

**Comment by highkite** [comment]
Hello @ObjectJosh, we can talk via IRC. Network irc.freenode.net I created a temporary channel: #githubAlphaBot 

But I didn't work on the the alphabot project for years. So I am not sure, whether I can really help.

**Comment by ObjectJosh** [comment]
Sounds good. Not sure how freenode works, but I joined it. It says I'm the only one in the group, so feel free to join when available

**Comment by highkite** [comment]
Hey @ObjectJosh I think due to the time difference IRC is not a working. Maybe email is a better option (highway.ita07 (_at_) web.de)
