### ISSUE TITLE
Can we use it in Angular 9?

### ISSUE THREAD

**Issue by ckvnahsik** [highkite/pdfAnnotate#17]
Hello,

I read your document, And I really appreciated your work.

I have some concern about how to use this library into Angular 9 project

I have install using nmp and import package, that you have suggested in docs but getting compile error'

What I did is,

1. Import lib in component
`import {AnnotationFactory} from 'annotpdf';`

2. Inject it in providers
`providers:[AnnotationFactory]`

3. Used it in constructor

```
AnnotationFactory.loadFile(this.fileUrl).then((factory) => {
        this.annotationFactory.createTextAnnotation(0, [50, 50], "Pop up note", "Max")
        this.annotationFactory.download()
})
```
Thanks,
Your help if highly appreciated

![image](https://user-images.githubusercontent.com/33306886/102538584-5e8c4f80-40a4-11eb-96be-92a2449b0bb3.png)

**Comment by highkite** [comment]
Hello @ckvnahsik you need to add
`"browser" : {
   "fs": false
}`

to the package.json file of your angular project.
