### ISSUE TITLE
Is it possible to view the annotation on the browser? label:question

### ISSUE THREAD

**Issue by nithinsyriac123** [highkite/pdfAnnotate#2]
I cloned the repo and opened the `pdfjsExample.html` file in the examples directory. I tried adding some annotations and downloading the file. I am able to view the annotations in the downloaded file; however is it possible to view the annotation on the viewer in the browser?

**Comment by highkite** [comment]
The example uses the PDFjs library. Unfortunately this PDF renderer does not support all the annotation types, as for instance FreeText annotations are not displayed.

Adding rendering support to PDFjs for displaying these annotations is a bit out of scope of this library. 
However, I suggest either implementing the feature and provide it to the PDFjs team or you can create a canvas layer on top of your PDF and render the annotations completely without PDFjs. The pdfAnnotate library provides a function to return all existing annotations in a PDF.

**Comment by vipulwairagade** [comment]
Hi @highkite  , The example is pretty cool ! But I have problem, I want to show the annotations in browser as mentioned in the issue and you mentioned this can be done with the canvas. Can you please guide a bit on this. 
Thanks in advance.

**Comment by Abhishek-maurya-19** [comment]
> Hi @highkite , The example is pretty cool ! But I have problem, I want to show the annotations in browser as mentioned in the issue and you mentioned this can be done with the canvas. Can you please guide a bit on this.
> Thanks in advance.

Hello @highkite  , hope you are doing well. As asked by @vipulwairagade , i also want some guidance in putting canvas layer on top of PDF and rendering the annotations completely without PDFjs.
