### ISSUE TITLE
createFreeTextAnnotation doesn't set a "print" PDF flag

### ISSUE THREAD

**Issue by pbek** [highkite/pdfAnnotate#24]
Thank you for this great library! It is just what I was looking for, because it doesn't break electronic signatures in the PDF!

I see in `createFreeTextAnnotation` you don't set a print flag...

https://github.com/highkite/pdfAnnotate/blob/576b0284b32890752a08ea7117c335e9f5b3048a/src/annotation.ts#L290-L300

...like you did in e.g. `createTextAnnotation`: 

https://github.com/highkite/pdfAnnotate/blob/576b0284b32890752a08ea7117c335e9f5b3048a/src/annotation.ts#L161)

Is there a reason for that? It prevents the annotation to be printed.

Other PDF applications, like Adobe Reader, Apple Preview or KDE Okular are setting the print flag for free text annotations.

**Comment by pbek** [comment]
And on a side note: You also don't seem to set the `color` in `createFreeTextAnnotation`... 😅

**Comment by pbek** [comment]
I created a PR for the print flag: https://github.com/highkite/pdfAnnotate/pull/25

**Comment by pbek** [comment]
...and a PR for the color: #26

**Comment by highkite** [comment]
Merged in version 1.0.14
