### ISSUE TITLE
Issue in Highlight Text Annotation

### ISSUE THREAD

**Issue by ANUBHAVNATANI** [highkite/pdfAnnotate#30]
When adding highlight text annotation with selected text from multiple pages, a bright bar comes in the page's footer. With no highlight on the next page.

**Comment by highkite** [comment]
Hi @ANUBHAVNATANI are you sure that this is a problem of the library? You can specify the highlighted areas using the quadpoints. Alternatively you can create multiple independent annotations. However, the rendere as pdfjs or acroread is responsible for the correct presentation.
