### ISSUE TITLE
Annotations not PDF/A compliant

### ISSUE THREAD

**Issue by pbek** [highkite/pdfAnnotate#33]
When you use for example a Text or FreeText annotation on a PDF/A (note that the latter also needs to have the print flag set to be PDF/A compilant, see #24) [VeraPDF](https://demo.verapdf.org/) is complaining about EOL markers.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1798101/110466599-4130b580-80d6-11eb-8214-a46d7713d220.png">

See: <https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-632-1>

Example pdf with FreeText annotation: [pdfa-sig-freetext.pdf](https://github.com/highkite/pdfAnnotate/files/6108266/pdfa-sig-freetext.pdf) (The PDF/A was created in LibreOffice Writer, then qualifiedly signed by me and then annotated with pdfAnnotate.)

What I found out after a longer hex-editor session was:

- after `obj` you must not use a space character (0x20), but an EOL marker (like 0x0A)
- in front of `endobj` you must not use a space character (0x20), but an EOL marker (like 0x0A)

**Comment by pbek** [comment]
I created a PR for it, #34.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1798101/110470042-a8506900-80da-11eb-83d1-b292f98bda11.png">

**Comment by pbek** [comment]
If anyone needs this direly, I've made a npm.js packages for this fix (and #24 and #25): https://www.npmjs.com/package/@digital-blueprint/annotpdf

**Comment by pbek** [comment]
The signature of the resulting pdf ([pdfa-sig-freetext.autofix.pdf](https://github.com/highkite/pdfAnnotate/files/6108653/pdfa-sig-freetext.autofix.pdf)) is still valid:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1798101/110474387-e603c080-80df-11eb-9ff6-61f087f5c2ca.png">

Try yourself: https://www.rtr.at/TKP/was_wir_tun/vertrauensdienste/Signatur/signaturpruefung/Pruefung.en.html

**Comment by highkite** [comment]
Included in version 1.0.14

**Comment by pbek** [comment]
Great, thank you! 😁
