### ISSUE TITLE
 annotate 'contents' not support chinese characters

### ISSUE THREAD

**Issue by MarkMindCkm** [highkite/pdfAnnotate#57]
when `contents` contains  chinese characters , it display as garbled code

![test](https://user-images.githubusercontent.com/18719494/147402020-7465e420-d554-4050-9202-6c80cda77c4f.gif)

**Comment by MarkMindCkm** [comment]
I have solved the problem by myself.

**Comment by z-yanqing** [comment]
Hi, can you share how to solve it?

**Comment by FyrikCN** [comment]
Hi, how did you solve it? I couldn't see any configuration about it..
