### ISSUE TITLE
Freetext annotations with default `ApperanceStream`s always have bg-color fills

### ISSUE THREAD

**Issue by binury** [highkite/pdfAnnotate#75]
Background colors for freetext appearance streams were added in this commit: 
https://github.com/highkite/pdfAnnotate/commit/44c897b89dd52d408efc2e2f2888c5b5da5a550d#diff-99b71d49cca1b89ae537b182ba0eadeed3fd7de3f90327fb110be965ab7ef7b1R247-R248
It seems like, with the changes on these two lines, it is no longer possible to add freetext annotations without a background/border. I.e. just text. Was this change made out of necessity for visibility?

Since fill colors in PDFs are RGB, there is no way to specify a transparent color with 0 alpha in order to prevent the black default from overriding.

Removing these lines did not seem to have any adverse effect, removed the undesired bg-color fill of the rect, and the annotation was still visible on all of the readers we tested, FWIW…
(But of course only provides a workaround and prevents any fill)

```js
  const annotFactory = new AnnotationFactory(pdf);
  const annot = annotFactory.createFreeTextAnnotation({
    page: 0,
    rect: [100, 100, 200, 200],
    contents: 'Hello World',
  });
  annot.createDefaultAppearanceStream();
  annotFactory.save('annotated.pdf');
  ```

**Comment by awolfson87** [comment]
@binury Did you ever find a solution for this?

**Comment by binury** [comment]
Forked the project and removed the default fill
